//LOCALHOST

//get all directors
GET http://localhost:8080/directors

//POST - New a director
### RANK 11
POST http://localhost:8080/directors HTTP/1.1
Content-Type: application/json

{ 
    "name": "Joss Whedon",
    "birthday": "6/23/1964",    
    "nationality": "American",
    "knownFor": "The Avengers, Angel, The Cabin in the Woods"
          
}

//PUT - Update a director
### 
PUT http://localhost:8080/directors HTTP/1.1
Content-Type: application/json

{
    
    "name": "Joss Whedon",
    "birthday": "6/23/1964",    
    "nationality": "American",
    "knownFor": "The Avengers, Angel, The Cabin in the Woods"
          

}


//get all movies
###
GET http://localhost:8080/movies

//getting only one movie by its id
### RANK 1
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f1

### RANK 2
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f1a

### RANK 3
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f1b

### RANK 4
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f1c

### RANK 5
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f1d

### RANK 6
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f1e

### RANK 7
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f1f

### RANK 8
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f20

### RANK 9
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f20

### RANK 10
GET http://localhost:8080/movies/63c6c28f22e2e813e3492f22


//POST - New a movie
### RANK 11
POST http://localhost:8080/movies HTTP/1.1
Content-Type: application/json

{ 

    "rank": "11",
    "title": "Furious 7",
    "director":"",
    "yearRelease": "2015",
    "rated": "PG-13",
    "budget": "$190,000,000",
    "lifeTimeGross":"$1,515,341,399"

}

//PUT - Update a movie
### 
PUT http://localhost:8080/movies/63c8832ac7ebfa357101cdb2 HTTP/1.1
Content-Type: application/json

{
    
    "rank": "11",
    "title": "Furious 7",
    "director":"",
    "yearRelease": "2015",
    "rated": "PG-13",
    "budget": "$190,000,000",
    "lifeTimeGross":"$1,515,341,399"

}

//DELETE movie
###
DELETE http://localhost:8080/movies/63c8832ac7ebfa357101cdb2 HTTP/1.1

//Render
###
GET https://cse341movies-app.onrender.com/movies




